# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Naorf\Documents\GitHub\Room_Management\src\UI\UI_Files\frame_titles.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
	def setupUi(self, Form):
		Form.setObjectName("Form")
		Form.resize(1300, 200)
		self.frame_titles = QtWidgets.QFrame(Form)
		self.frame_titles.setEnabled(True)
		self.frame_titles.setGeometry(QtCore.QRect(0, 30, 1290, 100))
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.frame_titles.sizePolicy().hasHeightForWidth())
		self.frame_titles.setSizePolicy(sizePolicy)
		self.frame_titles.setFrameShape(QtWidgets.QFrame.StyledPanel)
		self.frame_titles.setFrameShadow(QtWidgets.QFrame.Raised)
		self.frame_titles.setObjectName("frame_titles")
		self.number_title = QtWidgets.QLabel(self.frame_titles)
		self.number_title.setGeometry(QtCore.QRect(30, 10, 150, 50))
		self.number_title.setStyleSheet("border-radius:15px;\n"
		                                "font-size:21px;\n"
		                                "background-color:rgba(13, 153, 255,0.4);\n"
		                                "color: rgb(255, 255, 255);\n"
		                                "\n"
		                                "border:2px solid  rgb(255, 255, 255);\n"
		                                "border-radius:10px;")
		self.number_title.setObjectName("number_title")
		self.capacity_title = QtWidgets.QLabel(self.frame_titles)
		self.capacity_title.setGeometry(QtCore.QRect(210, 10, 150, 50))
		self.capacity_title.setStyleSheet("border-radius:15px;\n"
		                                  "font-size:21px;\n"
		                                  "background-color:rgba(13, 153, 255,0.4);\n"
		                                  "color: rgb(255, 255, 255);\n"
		                                  "\n"
		                                  "border:2px solid  rgb(255, 255, 255);\n"
		                                  "border-radius:10px;")
		self.capacity_title.setObjectName("capacity_title")
		self.now_status_title = QtWidgets.QLabel(self.frame_titles)
		self.now_status_title.setGeometry(QtCore.QRect(390, 10, 200, 50))
		self.now_status_title.setStyleSheet("border-radius:15px;\n"
		                                    "font-size:21px;\n"
		                                    "background-color:rgba(13, 153, 255,0.4);\n"
		                                    "color: rgb(255, 255, 255);\n"
		                                    "\n"
		                                    "border:2px solid  rgb(255, 255, 255);\n"
		                                    "border-radius:10px;")
		self.now_status_title.setObjectName("now_status_title")
		self.cleanning_status_title = QtWidgets.QLabel(self.frame_titles)
		self.cleanning_status_title.setGeometry(QtCore.QRect(620, 10, 230, 50))
		self.cleanning_status_title.setStyleSheet("border-radius:15px;\n"
		                                          "font-size:21px;\n"
		                                          "background-color:rgba(13, 153, 255,0.4);\n"
		                                          "color: rgb(255, 255, 255);\n"
		                                          "\n"
		                                          "border:2px solid  rgb(255, 255, 255);\n"
		                                          "border-radius:10px;")
		self.cleanning_status_title.setObjectName("cleanning_status_title")
		self.faults_title = QtWidgets.QLabel(self.frame_titles)
		self.faults_title.setGeometry(QtCore.QRect(880, 10, 130, 50))
		self.faults_title.setStyleSheet("border-radius:15px;\n"
		                                "font-size:21px;\n"
		                                "background-color:rgba(13, 153, 255,0.4);\n"
		                                "color: rgb(255, 255, 255);\n"
		                                "\n"
		                                "border:2px solid  rgb(255, 255, 255);\n"
		                                "border-radius:10px;")
		self.faults_title.setObjectName("faults_title")
		self.dates_catch_title = QtWidgets.QLabel(self.frame_titles)
		self.dates_catch_title.setGeometry(QtCore.QRect(1040, 10, 240, 50))
		self.dates_catch_title.setStyleSheet("border-radius:15px;\n"
		                                     "font-size:21px;\n"
		                                     "background-color:rgba(13, 153, 255,0.4);\n"
		                                     "color: rgb(255, 255, 255);\n"
		                                     "\n"
		                                     "border:2px solid  rgb(255, 255, 255);\n"
		                                     "border-radius:10px;")
		self.dates_catch_title.setObjectName("dates_catch_title")
		
		self.retranslateUi(Form)
		QtCore.QMetaObject.connectSlotsByName(Form)
	
	def retranslateUi(self, Form):
		_translate = QtCore.QCoreApplication.translate
		Form.setWindowTitle(_translate("Form", "Form"))
		self.number_title.setText(_translate("Form", "Room number"))
		self.capacity_title.setText(_translate("Form", "Room capacity"))
		self.now_status_title.setText(_translate("Form", "Room status (NOW)"))
		self.cleanning_status_title.setText(_translate("Form", "Room cleanning status"))
		self.faults_title.setText(_translate("Form", "Room faults"))
		self.dates_catch_title.setText(_translate("Form", "Dates the room is catch"))


if __name__ == "__main__":
	import sys
	
	app = QtWidgets.QApplication(sys.argv)
	Form = QtWidgets.QWidget()
	ui = Ui_Form()
	ui.setupUi(Form)
	Form.show()
	sys.exit(app.exec_())
